export const URLS = {
  HOME_PAGE_VEDIO: "shared/global_variables/?key=HOME_PAGE_VIDEO",
  REGISTER: "/auth/signup/",
  LOGIN: "/auth/signin/",
  FORGOT_PASSWORD: "/auth/forgot-password/",
  RESET_PASSWORD: "/auth/password-reset-confirm/MQ/",
  TRAINERS: "auth/users/?account_type=TRAINER&is_verified=True",
  PROGRAMS: "/program",
  TRAINER_BIOGRAPHY_BIDEO: "/auth/users/?account_type=TRAINER&is_verified=True",
  MONTHS: "/program/month",
  GALLERY: "/program/program-data/",
  GET_PAYEMNT: "/payments/subscriptions/?status=incomplete",
  DELETE_INCOMPLETE_PAYMENT: "/payments/subscriptions/delete/",
  GET_SUBSCRIPTION: "/payments/subscriptions/subscription/",
  GET_Search: "/program/summary/",
  GET_GALLERY: "/program/summary/?ordering=user_id",
  POST_WATCHING: "/program/main-video/watched-seconds/",
  UPDATE_WATCHING: "/program/main-video/watched-seconds/",
  UPDATE_WATCHING_TIP: "/program/tip-video/watched-seconds/",
  GET_WATCHING: "/program/main-video/watched-seconds/",
  GET_WATCHING_TIP: "/program/tip-video/watched-seconds/",
  ACCOUNT_TYPE: "/auth/profile/",
  BONUS_CATEGORY: "/program/category/?name=bonus",
  BONUS_ID: "/program/",
  ME: "/auth/me/",
  UPDATE_PROFILE: "/auth/update/",
  CATEGORES: "/v1/inventory/categories/",
  ADD_PRODUCT: "/v1/inventory/products/",
  PRODUCTS: "/v1/inventory/products",
  PRODUT_DETAIL: "/v1/inventory/products/",
  UPDATE_PRODUCT: "/v1/inventory/products/",
  DELETE_PRODUCT: "/v1/inventory/products",
  UPLOAD_PORODUCTS: "/v1/inventory/upload-products/",
  STATS: "/v1/inventory/stats/",
  TRANSACTIONS: "/v1/transactions/",
  TRANSACTIONS_SUMMARY: "/v1/transactions/summary/",
  REPORTS_EXPENSES: "/v1/reports/expenses/",
  LIVE_INVENTORY: "v1/report/live-inventory/",
  BEST_SELLING: "/v1/reports/best-selling/",
  STOCK_AGING: "/v1/reports/stock-aging/",
  PURCHASE_SALES: "/v1/reports/purchase-sales/",
  MONTHLY_PROFIT: "/v1/reports/monthly-profit/",
  REPORT_STATE: "/v1/reports/stats/",
  EXPENSES: "/v1/reports/expenses/",
  CARDS: "/v1/cards/",
  INVOICE: "/v1/invoices/",
  CUSTOMERS: "/v1/customers/",
  DASHBOARD_STATS: "/v1/dashboard/stats/",
  SOLD_ITEMS: "/v1/dashboard/sold-items/",
  DASHBOARD_INCOME_BREAKDONW: "/v1/dashboard/income-breakdown/",
  DASHBOARD_EXPENSE_TRACKING: "/v1/dashboard/expense-tracking/",
  // DASHBOARD_DETAILED_ANALYTICS: "/v1/dashboard/detailed-analytics/",
  // MARKET_COMPARISON: "/v1/market-insightsmarket-comparison/",
  MARKET_COMPARISON: "/v1//market-data/inventory_based_comparison/",
  PLANS: "/plans/",
  SUBSCRBE: "/subscribe/",
  SUBSCRIPTION_DETAILS: "/subscription/details/",
  MARKAS_SOLD: "/v1/inventory/bulk-mark-sold/",
  BULK_OPERATION: "/v1/inventory/bulk-operations/",
};

export const METHODS = {
  POST: "POST",
  GET: "GET",
  PUT: "PUT",
  DELETE: "DELETE",
  PATCH: "PATCH",
} as const

export type METHODTYPES = keyof typeof METHODS;

